import React from "react";
import "./styles/app.css";
import { SideBar } from "./components";
import { StyledSideBar, StyledLayout, StyledMainLayout } from "./styles/App";

import { BrowserRouter as Router, Route, Routes } from "react-router-dom";

function App() {
  return (
    <>
      <Router>
        <Routes>
          <Route path="/overview/qwer1"></Route>
          <Route path="/overview/qwer2"></Route>
          <Route path="/qwer3"></Route>
        </Routes>
        <StyledLayout className="layout">
          <StyledSideBar className="side-bar">
            <SideBar />
          </StyledSideBar>
          <StyledMainLayout className="main-layout">
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
            <h1>Hello world</h1>
          </StyledMainLayout>
        </StyledLayout>
      </Router>
    </>
  );
}

export default App;
